- name: Deploy Backend
  uses: appleboy/ssh-action@master
  with:
    host: ${{ secrets.EC2_HOST }}
    username: ubuntu
    key: ${{ secrets.EC2_KEY }}
    script: |
      cd hello-cicd-project/backend
      git pull
      npm install
      pm2 restart all
